version: "3"
services:
  web_flask:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - "./src:/scripts"
    environment:
      TZ: "Asia/Tokyo"
      FLASK_ENV: "development"
    tty: true
    command: >
      /bin/bash -c "
      cd /scripts &&
      pipenv install --system &&
      flask run --host 0.0.0.0 --port 5000"